//! `koxi.lock` — machine-written resolved state for `koxi.toml` sources:
//! exact url + sha256 per tarball, exact rev per git checkout. Written by
//! `setup`, never edited by hand.
//!
//! Compatibility: `version` is the reader floor. Tables this binary
//! does not know are carried through load/save untouched, so a newer
//! koxi may add tables without cutting off older readers; the version
//! bumps only when an existing table changes shape, and then older
//! readers refuse the file with a clear message instead of a parse
//! error. `tests/fixtures/lock_shape.toml` pins the shape of the
//! current version so a change cannot slip by without a decision.

use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::config::Source;

/// Default lock path, relative to the working directory.
pub const LOCK_PATH: &str = "koxi.lock";

/// Format version: the oldest reader that understands the tables as
/// laid out here. Bump when an existing table changes shape (see the
/// shape test); adding a table does not need one.
pub const LOCK_VERSION: u32 = 2;

const HEADER: &str =
    "# This file is @generated by koxi.\n# It is not intended for manual editing.\n";

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub struct Lock {
    pub version: u32,
    #[serde(default)]
    pub sources: BTreeMap<String, LockedSource>,
    /// sha256 of each build-input asset as last used, keyed by asset
    /// name; build steps rebuild when the hash moves. Assets are
    /// user-editable, so a moved hash is staleness, not an error.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub assets: BTreeMap<String, String>,
    /// Input fingerprint of each completed build (source sha +
    /// config sha), keyed by build target; a build is skipped only
    /// when its artifact exists and the fingerprint matches.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub builds: BTreeMap<String, String>,
    /// sha256 of each produced artifact (kernel image, harvested
    /// kernel modules, ...), keyed by artifact file name.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub artifacts: BTreeMap<String, String>,
    /// Tables written by a newer koxi, preserved verbatim so this
    /// binary's save never destroys them.
    #[serde(flatten, skip_serializing_if = "BTreeMap::is_empty")]
    pub extra: BTreeMap<String, toml::Value>,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(untagged)]
pub enum LockedSource {
    Tarball {
        version: String,
        url: String,
        sha256: String,
    },
    Git {
        git: String,
        /// The pin as declared in `koxi.toml` (commit hash or tag).
        rev: String,
        /// The exact commit the pin resolved to.
        commit: String,
    },
    GitMeta {
        #[serde(rename = "git-meta")]
        git_meta: String,
        /// The pin as declared in `koxi.toml` (commit hash or tag).
        rev: String,
        /// The exact commit the pin resolved to.
        commit: String,
    },
}

/// Just enough of a lock to read its version before committing to
/// the full shape.
#[derive(Deserialize)]
struct Header {
    version: u32,
}

impl Default for Lock {
    fn default() -> Self {
        Self {
            version: LOCK_VERSION,
            sources: BTreeMap::new(),
            assets: BTreeMap::new(),
            builds: BTreeMap::new(),
            artifacts: BTreeMap::new(),
            extra: BTreeMap::new(),
        }
    }
}

impl Lock {
    /// Read the lock; `Ok(None)` when the file does not exist yet.
    pub fn load(path: &Path) -> Result<Option<Self>, Error> {
        let text = match fs::read_to_string(path) {
            Ok(text) => text,
            Err(err) if err.kind() == io::ErrorKind::NotFound => return Ok(None),
            Err(err) => return Err(Error::Io(err)),
        };
        Self::parse(&text).map(Some)
    }

    pub fn parse(text: &str) -> Result<Self, Error> {
        // Version first: a newer, reshaped lock must say "newer than
        // this koxi", not fail on whatever field it reshaped.
        let header: Header = toml::from_str(text).map_err(Error::Parse)?;
        if header.version > LOCK_VERSION {
            return Err(Error::Version(header.version));
        }
        let mut lock: Self = toml::from_str(text).map_err(Error::Parse)?;
        // Older locks upgrade transparently: new tables default empty
        // and the next save writes the current version.
        lock.version = LOCK_VERSION;
        Ok(lock)
    }

    pub fn save(&self, path: &Path) -> Result<(), Error> {
        fs::write(path, self.render()?).map_err(Error::Io)
    }

    pub fn render(&self) -> Result<String, Error> {
        let body = toml::to_string_pretty(self).map_err(Error::Ser)?;
        Ok(format!("{HEADER}\n{body}"))
    }

    /// Whether `name` is locked consistently with its config declaration.
    pub fn satisfies(&self, name: &str, source: &Source) -> bool {
        match (self.sources.get(name), source) {
            (
                Some(LockedSource::Tarball { version, url, .. }),
                Source::Tarball {
                    version: cfg_version,
                    url: cfg_url,
                },
            ) => version == cfg_version && url == cfg_url,
            (
                Some(LockedSource::Git { git, rev, .. }),
                Source::Git {
                    git: cfg_git,
                    rev: cfg_rev,
                },
            ) => git == cfg_git && rev == cfg_rev,
            (
                Some(LockedSource::GitMeta { git_meta, rev, .. }),
                Source::GitMeta {
                    git_meta: cfg_url,
                    rev: cfg_rev,
                },
            ) => git_meta == cfg_url && rev == cfg_rev,
            _ => false,
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("reading lock: {0}")]
    Io(std::io::Error),
    #[error("parsing lock: {0}")]
    Parse(toml::de::Error),
    #[error("writing lock: {0}")]
    Ser(toml::ser::Error),
    #[error(
        "koxi.lock version {0} is newer than this koxi understands (max {LOCK_VERSION}); \
         upgrade koxi, or delete the lock to re-resolve every source"
    )]
    Version(u32),
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every table populated: the shape the fixture pins.
    fn sample() -> Lock {
        let mut lock = Lock::default();
        lock.sources.insert(
            "linux".into(),
            LockedSource::Tarball {
                version: "6.19".into(),
                url: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.19.tar.xz".into(),
                sha256: "0000000000000000000000000000000000000000000000000000000000000000".into(),
            },
        );
        lock.sources.insert(
            "linux-meta".into(),
            LockedSource::GitMeta {
                git_meta: "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
                    .into(),
                rev: "v6.19".into(),
                commit: "c0ffeec0ffeec0ffeec0ffeec0ffeec0ffeec0ff".into(),
            },
        );
        lock.sources.insert(
            "syzkaller".into(),
            LockedSource::Git {
                git: "https://github.com/google/syzkaller.git".into(),
                rev: "some-tag".into(),
                commit: "d34db33fd34db33fd34db33fd34db33fd34db33f".into(),
            },
        );
        lock.assets.insert("linux/config".into(), "a".repeat(64));
        lock.builds
            .insert("linux-x86_64".into(), "r4:src:cfg:gcc".into());
        lock.artifacts.insert("bzImage".into(), "b".repeat(64));
        lock
    }

    #[test]
    fn older_lock_versions_upgrade_and_newer_are_rejected() {
        let lock = Lock::parse("version = 1\n").unwrap();
        assert_eq!(lock.version, LOCK_VERSION, "older lock upgraded");

        // A reshaped future lock reports its version, not a field error.
        let future = "version = 99\n[sources.linux]\nshape = \"unknown\"\n";
        assert!(matches!(Lock::parse(future), Err(Error::Version(99))));
        assert!(Lock::parse(future)
            .unwrap_err()
            .to_string()
            .contains("upgrade koxi"));
    }

    #[test]
    fn unknown_tables_survive_a_round_trip() {
        let text = format!(
            "version = {LOCK_VERSION}\n\n[sources.linux]\nversion = \"6.19\"\nurl = \"u\"\n\
             sha256 = \"s\"\n\n[future]\nknob = 1\n"
        );
        let lock = Lock::parse(&text).unwrap();
        assert_eq!(lock.extra["future"]["knob"], toml::Value::Integer(1));
        let again = Lock::parse(&lock.render().unwrap()).unwrap();
        assert_eq!(again, lock, "preserved verbatim through save");
    }

    #[test]
    fn round_trips_through_toml() {
        let lock = sample();
        let parsed = Lock::parse(&lock.render().unwrap()).unwrap();
        assert_eq!(lock, parsed);
    }

    /// The pinned shape of LOCK_VERSION. If this fails you changed
    /// how a table serializes: decide whether older readers still
    /// parse it (then only update the fixture) or not (then bump
    /// LOCK_VERSION and update the fixture).
    #[test]
    fn shape_matches_the_pinned_fixture() {
        let pinned = include_str!("../tests/fixtures/lock_shape.toml");
        let rendered = sample().render().unwrap();
        assert_eq!(
            rendered, pinned,
            "koxi.lock shape drifted from tests/fixtures/lock_shape.toml (LOCK_VERSION {LOCK_VERSION}):\n\
             \n{rendered}"
        );
        assert_eq!(Lock::parse(pinned).unwrap(), sample());
    }
}
