//! `koxi.lock` — machine-written resolved state for `koxi.toml` sources:
//! exact url + sha256 per tarball, exact rev per git checkout. Written by
//! `setup`, never edited by hand.

use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::io;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::config::{Config, Source};

/// Default lock path, relative to the working directory.
pub const LOCK_PATH: &str = "koxi.lock";

/// Format version, bumped whenever a lock table changes shape
/// (deny_unknown_fields makes older binaries hard-fail on newer
/// locks; loading older versions upgrades them transparently).
const LOCK_VERSION: u32 = 2;

const HEADER: &str =
    "# This file is @generated by koxi.\n# It is not intended for manual editing.\n";

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Lock {
    pub version: u32,
    #[serde(default)]
    pub sources: BTreeMap<String, LockedSource>,
    /// sha256 of each build-input asset as last used, keyed by asset
    /// name; build steps rebuild when the hash moves. Assets are
    /// user-editable, so a moved hash is staleness, not an error.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub assets: BTreeMap<String, String>,
    /// Input fingerprint of each completed build (source sha +
    /// config sha), keyed by build target; a build is skipped only
    /// when its artifact exists and the fingerprint matches.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub builds: BTreeMap<String, String>,
    /// sha256 of each produced artifact (kernel image, harvested
    /// kernel modules, ...), keyed by artifact file name.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub artifacts: BTreeMap<String, String>,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(untagged)]
pub enum LockedSource {
    Tarball {
        version: String,
        url: String,
        sha256: String,
    },
    Git {
        git: String,
        /// The pin as declared in `koxi.toml` (commit hash or tag).
        rev: String,
        /// The exact commit the pin resolved to.
        commit: String,
    },
    GitMeta {
        #[serde(rename = "git-meta")]
        git_meta: String,
        /// The pin as declared in `koxi.toml` (commit hash or tag).
        rev: String,
        /// The exact commit the pin resolved to.
        commit: String,
    },
}

impl Default for Lock {
    fn default() -> Self {
        Self {
            version: LOCK_VERSION,
            sources: BTreeMap::new(),
            assets: BTreeMap::new(),
            builds: BTreeMap::new(),
            artifacts: BTreeMap::new(),
        }
    }
}

impl Lock {
    /// Read the lock; `Ok(None)` when the file does not exist yet.
    pub fn load(path: &Path) -> Result<Option<Self>, Error> {
        let text = match fs::read_to_string(path) {
            Ok(text) => text,
            Err(err) if err.kind() == io::ErrorKind::NotFound => return Ok(None),
            Err(err) => return Err(Error::Io(err)),
        };
        let mut lock: Self = toml::from_str(&text).map_err(Error::Parse)?;
        if lock.version > LOCK_VERSION {
            return Err(Error::Version(lock.version));
        }
        // Older locks upgrade transparently: new tables default empty
        // and the next save writes the current version.
        lock.version = LOCK_VERSION;
        Ok(Some(lock))
    }

    pub fn save(&self, path: &Path) -> Result<(), Error> {
        let body = toml::to_string_pretty(self).map_err(Error::Ser)?;
        fs::write(path, format!("{HEADER}\n{body}")).map_err(Error::Io)
    }

    /// Whether `name` is locked consistently with its config declaration.
    pub fn satisfies(&self, name: &str, source: &Source) -> bool {
        match (self.sources.get(name), source) {
            (
                Some(LockedSource::Tarball { version, url, .. }),
                Source::Tarball {
                    version: cfg_version,
                    url: cfg_url,
                },
            ) => version == cfg_version && url == cfg_url,
            (
                Some(LockedSource::Git { git, rev, .. }),
                Source::Git {
                    git: cfg_git,
                    rev: cfg_rev,
                },
            ) => git == cfg_git && rev == cfg_rev,
            (
                Some(LockedSource::GitMeta { git_meta, rev, .. }),
                Source::GitMeta {
                    git_meta: cfg_url,
                    rev: cfg_rev,
                },
            ) => git_meta == cfg_url && rev == cfg_rev,
            _ => false,
        }
    }

    /// Config sources not consistently locked yet — what `setup` must resolve.
    pub fn stale<'c>(&self, config: &'c Config) -> Vec<&'c str> {
        config
            .sources
            .iter()
            .filter(|(name, source)| !self.satisfies(name, source))
            .map(|(name, _)| name.as_str())
            .collect()
    }
}

#[derive(Debug)]
pub enum Error {
    Io(std::io::Error),
    Parse(toml::de::Error),
    Ser(toml::ser::Error),
    Version(u32),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::Io(err) => write!(f, "reading lock: {err}"),
            Error::Parse(err) => write!(f, "parsing lock: {err}"),
            Error::Ser(err) => write!(f, "writing lock: {err}"),
            Error::Version(found) => {
                write!(
                    f,
                    "lock version {found} is newer than this koxi (max {LOCK_VERSION})"
                )
            }
        }
    }
}

impl std::error::Error for Error {}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Lock {
        let mut lock = Lock::default();
        lock.sources.insert(
            "linux".into(),
            LockedSource::Tarball {
                version: "6.19".into(),
                url: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.19.tar.xz".into(),
                sha256: "0000000000000000000000000000000000000000000000000000000000000000".into(),
            },
        );
        lock.sources.insert(
            "syzkaller".into(),
            LockedSource::Git {
                git: "https://github.com/google/syzkaller.git".into(),
                rev: "some-tag".into(),
                commit: "d34db33fd34db33fd34db33fd34db33fd34db33f".into(),
            },
        );
        lock
    }

    #[test]
    fn older_lock_versions_upgrade_and_newer_are_rejected() {
        let dir = std::env::temp_dir().join(format!("koxi-lock-ver-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("koxi.lock");

        std::fs::write(&path, "version = 1\n").unwrap();
        let lock = Lock::load(&path).unwrap().unwrap();
        assert_eq!(lock.version, 2, "older lock upgraded");

        std::fs::write(&path, "version = 99\n").unwrap();
        assert!(matches!(Lock::load(&path), Err(Error::Version(99))));
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn round_trips_through_toml() {
        let lock = sample();
        let text = toml::to_string_pretty(&lock).unwrap();
        let parsed: Lock = toml::from_str(&text).unwrap();
        assert_eq!(lock, parsed);
    }

    #[test]
    fn stale_reports_changed_and_missing_sources() {
        let lock = sample();
        let config = Config::parse(
            r#"
            [sources.linux]
            version = "6.19"
            url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.19.tar.xz"

            [sources.busybox]
            version = "1.36.1"
            url = "https://busybox.net/downloads/busybox-1.36.1.tar.bz2"

            [sources.syzkaller]
            git = "https://github.com/google/syzkaller.git"
            rev = "some-tag"
            "#,
        )
        .unwrap();
        assert_eq!(lock.stale(&config), vec!["busybox"]);

        let pinned_elsewhere = Config::parse(
            r#"
            [sources.syzkaller]
            git = "https://github.com/google/syzkaller.git"
            rev = "0ther"
            "#,
        )
        .unwrap();
        assert_eq!(pinned_elsewhere.sources.len(), 1);
        assert_eq!(lock.stale(&pinned_elsewhere), vec!["syzkaller"]);
    }
}
